config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :restaurants do
    resources :reviews, only: %i[new create]
  end
    # A REFACTO
  # get 'restaurants', to: 'restaurants#index'
  # get 'restaurants/new', to: 'restaurants#new', as: :new_restaurant
  # post 'restaurants', to: 'restaurants#create'
  # get 'restaurants/:id', to: 'restaurants#show', as: :restaurant

  # A REFACTO
  # get 'restaurants/:restaurant_id/reviews/new', to: 'reviews#new', as: :new_review
  # post 'restaurants/:restaurant_id/reviews', to: 'reviews#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy

  validates :name, :address, :category, presence: { message: 'champ obligatoire' }
  validates :category, inclusion: { in: %w[chinese italian japanese french belgian], message: 'choose between chinese italian japanese french belgian' }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, :rating, presence: { message: 'champ obligatoire' }
  validates :rating, numericality: { in: (0..5), only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to @restaurant, notice: 'Allons découvrir maintenant !'
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @review = Review.new
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def create
    @review = Review.new(set_review)
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review.restaurant = @restaurant
    if @review.save
      redirect_to @restaurant
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def set_review
    params.require(:review).permit(:rating, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for(restaurant) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :phone_number %>
  <%= f.input :category %>
  <%= f.submit %>
<% end %>

app/views/restaurants/index.html.erb
<div class="container m-5">
<h1>Welcome</h1>
<% @restaurants.each do |restaurant| %>
<li class="row"><%= link_to restaurant.name, restaurant_path(restaurant) %></li>
<% end %>
</div>

<%= link_to "Add a new restaurant", new_restaurant_path %>

app/views/restaurants/new.html.erb
<%= render "form", restaurant: @restaurant %>

app/views/restaurants/show.html.erb
<h2><%= @restaurant.name %></h2>
<li><%= @restaurant.address %></li>
<li><%= @restaurant.phone_number %></li>
<li>Type : <%= @restaurant.category %></li>

<%= link_to "Ajouter un avis",  new_restaurant_review_path(@restaurant) %>


<%# le form n'a pu lieu d'exister ds l'arborescence de review si on le met ici%>
<%# <%= simple_form_for([@restaurant, @review]) do |f| %>
  <%# <%= f.input :rating %>
  <%# <%= f.input :content %>
  <%# <%= f.submit %>
<%# <% end %>



<div>
<% @restaurant.reviews.each do |review| %>
<p><%= review.rating %> - <%= review.content %></p>
<% end %>
</div>


<%= link_to "Retour à la liste", restaurants_path %>

app/views/reviews/_form.html.erb
<%= simple_form_for([@restaurant, @review]) do |f| %>
  <%= f.input :rating %>
  <%= f.input :content %>
  <%= f.submit %>
<% end %>

app/views/reviews/new.html.erb
<%= render "form", review: @review %>

<%= link_to "Retour à la fiche du restaurant", restaurant_path(@restaurant) %>
<%= link_to "Retour à la liste", restaurants_path %>